In [11]:
import pandas as pd
import numpy as np 
import string

In [8]:
dwarves = open("Dwarf Names Training Data.txt","r")
dwarf_names = []
for dwarf in dwarves:
    dwarf_stripped = dwarf.rstrip()
    dwarf_names.append(dwarf_stripped)
    
print(dwarf_names)

['May', 'Adaldrida', 'Celendine', 'Gloriana', 'Pimpernel', 'Tanta', 'Alfrida', 'Cora', 'Goldilocks', 'Melba', 'Poppy', 'Yolanda', 'Amalda', 'Cornelia', 'Grimalda', 'Melilot', 'Prima', 'Amaranth', 'Chica', 'Hilda', 'Melissa', 'Primrose', 'Amethyst', 'Daisy', 'Jasmine', 'Menegilda', 'Primula', 'Angelica', 'Diamanda', 'Jemima', 'Mentha', 'Prisca', 'Arabella', 'Diamond', 'Jessamine', 'Mimosa', 'Regina', 'Asphodel', 'Dina', 'Lalia', 'Mirabella', 'Rhoda', 'Belba', 'Donnamira', 'Laura', 'Miranda', 'Robinia', 'Belinda', 'Dora', 'Lavinia', 'Myrtle', 'Rosa', 'Bellisima', 'Duenna', 'Lily', 'Nina', 'Rosamunda', 'Bell', 'Eglantine', 'Linda', 'Nora', 'Rose', 'Belladonna', 'Elanor', 'Lobelia', 'Pamphila', 'Rowan', 'Bertha', 'Esmeralda', 'Malva', 'Pandora', 'Ruby', 'Berylla', 'Estella', 'Marigold', 'Pansy', 'Salvia', 'Camelia', 'Fatima', 'Mantissa', 'Pearl', 'Savanna', 'Cara', 'Gerda', 'Matilda', 'Peony', 'Selina', 'Caramella', 'Gilly', 'Maxima', 'Pervinca', 'Semolina', 'Adelbert', 'Conrad', 'Gringamo

In [18]:
chars = string.ascii_lowercase
chars_num = len(chars)
print(chars_num)
print(chars)

26
abcdefghijklmnopqrstuvwxyz


In [19]:
max_length = 9
dwarf_length = len(dwarf_names)
char_to_id = {c:i for i, c in enumerate(chars)}
id_to_char = {v:k for k, v in enumerate(chars)}
print(char_to_id)
print(id_to_char)

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}
{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [21]:
X = np.zeros((dwarf_length,max_length,chars_num))
Y = np.zeros((dwarf_length,max_length,chars_num))
print(X)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
